"use strict";
const $ = (id) => document.getElementById(id);
const statusLabels = {queued:"排队中",control_queued:"控制队列",running:"执行中",succeeded:"已完成",failed:"失败",partial:"部分完成",awaiting_confirmation:"待确认",cancelled:"已取消",unknown:"结果未知",pending:"待确认",expired:"已过期",executing:"正在执行",reconciled:"已核对"};
const kindLabels = {intent:"识别请求",intent_guard:"请求保护",tool:"读取工具",model:"模型调用",diagnosis:"诊断结论",operation_prepared:"生成待确认操作",operation:"操作结果",error:"异常记录"};
const toolLabels = {system:"服务器概况",services:"服务列表",inspect:"容器状态",logs:"日志摘要",health:"业务健康",ranking:"资源排行"};
const state = {items:[],next:null,selected:null,request:0,detailRequest:0};
function node(tag, cls, text) {const e=document.createElement(tag); if(cls)e.className=cls; if(text!==undefined)e.textContent=text; return e;}
function date(value){return value?new Date(value).toLocaleString("zh-CN",{hour12:false}):"未知";}
function notify(message){$("notice").textContent=message;$("notice").hidden=!message;}
function showLogin(){state.request++;state.detailRequest++;state.items=[];state.selected=null;$("tasks").replaceChildren();$("detail").replaceChildren(node("p","","选择一个任务查看证据与执行记录。"));if(typeof clearEvidence==="function")clearEvidence();$("stats").replaceChildren();$("workspace").hidden=true;$("logout").hidden=true;$("login-view").hidden=false;}
async function api(path, options={}){const res=await fetch("/admin/api/"+path,{credentials:"same-origin",cache:"no-store",...options});const data=await res.json();if(!res.ok){if(res.status===401)showLogin();throw new Error(data.message||"请求失败，请重试");}return data;}
function badge(status){return node("span","badge "+status,statusLabels[status]||status);}
function title(task){const i=task.intent||{};return [({query:"查询",diagnose:"只读排查",operation:"操作请求",clarify:"请求澄清"})[i.kind]||"任务记录",i.target||"",i.action?({start:"启动",stop:"停止",restart:"重启"}[i.action]||i.action):""].filter(Boolean).join(" · ");}
function renderStats(counts){const sum=(keys)=>keys.reduce((s,k)=>s+(counts[k]||0),0);const stats=[["保留任务",Object.values(counts).reduce((a,b)=>a+b,0),"当前审计保留范围"],["已完成",sum(["succeeded"]),"任务完成状态，不等于诊断正确率"],["需要关注",sum(["failed","partial","unknown"]),"失败 / 部分完成 / 结果未知"],["待处理",sum(["queued","control_queued","running","awaiting_confirmation"]),"含待确认任务，请查看操作有效期"]];$("stats").replaceChildren(...stats.map(([label,count,note])=>{const box=node("div","stat");box.append(node("span","stat-label",label),node("strong","stat-number",count),node("small","",note));return box;}));}
function renderTasks(){const rows=state.items.map(task=>{const row=node("button","task"+(state.selected===task.id?" selected":""));row.type="button";row.setAttribute("aria-pressed",String(state.selected===task.id));const top=node("div","task-top");top.append(node("span","task-title",title(task)),badge(task.status));const meta=node("div","task-meta");meta.append(node("span","",date(task.created_at)),node("span","",task.channel==="wecom"?"企业微信":"内部任务"));row.append(top,meta,node("div","task-summary",task.result||"任务正在处理，尚无结果摘要"));row.addEventListener("click",()=>loadDetail(task.id));return row;});if(!rows.length){const empty=node("div","empty");empty.append(node("h2","","暂无记录"),node("p","","在企业微信发起任务后，可在这里查看审计记录。"));rows.push(empty);}$("tasks").replaceChildren(...rows);$("more").hidden=!state.next;$("list-caption").textContent=`已加载 ${state.items.length} 条 · 当前保留的审计记录`;}
function metric(label,value){const e=node("div","metric",label);e.append(node("b","",value));return e;}
function renderDetail(data){const {task,events,operation}=data;const root=$("detail");root.replaceChildren();const head=node("div","detail-heading");head.append(node("h2","",title(task)),badge(task.status));const exportButton=node("button","secondary","导出快照 ↓");exportButton.addEventListener("click",()=>downloadTask(task.id,exportButton));head.append(exportButton);root.append(head,node("div","detail-id",task.id));const tools=events.filter(e=>e.kind==="tool");const models=events.filter(e=>e.kind==="model");const elapsed=["queued","control_queued","running"].includes(task.status)?"未结束":((new Date(task.updated_at)-new Date(task.created_at))/1000).toFixed(1)+" s";const metrics=node("div","metric-row");metrics.append(metric("创建至最后更新",elapsed),metric("已记录工具",tools.length+" 次"),metric("已记录模型调用",models.length+" 次"));root.append(metrics,node("h3","","结果摘要"),node("div","result",task.result||"暂未生成结果"));if(operation){root.append(node("h3","","授权与操作"));let label=statusLabels[operation.status]||operation.status;if(operation.status==="pending" && new Date(operation.expires_at)<=new Date())label="待确认记录（已超过有效期）";root.append(node("div","result",`${operation.target} · ${operation.action}\n${label}\n有效期至 ${date(operation.expires_at)}\n操作仍须在企业微信确认；后台不提供确认码。`));}root.append(node("h3","","证据与执行时间线"));const list=node("ol","timeline");let evidence=0;for(const event of events){const item=node("li","event");const data=event.data||{};const head=node("div","event-head");let label=kindLabels[event.kind]||event.kind;if(event.kind==="tool")label+=` · ${toolLabels[data.call?.name]||data.call?.name||"未知"} · 记录 ${++evidence}`;head.append(node("strong","",label),node("time","",date(event.created_at)));item.append(head);const parts=[];if(data.duration_ms!==undefined)parts.push(`${data.duration_ms} ms`);if(data.model)parts.push(data.model);if(data.prompt_version)parts.push(data.prompt_version);if(data.stop_reason)parts.push(`停止原因：${data.stop_reason}`);if(parts.length)item.append(node("div","event-sub",parts.join(" · ")));const details=node("details");details.append(node("summary","","查看已保存的审计摘要"),node("pre","",JSON.stringify(data,null,2)));item.append(details);list.append(item);}root.append(list);if(!events.length)root.append(node("p","","暂无已保存的事件。"));root.append(node("p","footnote",data.events_truncated?"仅显示前 100 条事件，后续内容已截断。":"日志仅保留摘要，工具记录序号不是诊断 E 编号。工具读取失败可能只有最终诊断中的错误引用。"));}
async function loadDetail(id){state.selected=id;const version=++state.detailRequest;renderTasks();$("detail").replaceChildren(node("p","","正在读取任务记录…"));try{const data=await api("tasks/"+id);if(version===state.detailRequest)renderDetail(data);}catch(error){if(version===state.detailRequest)$("detail").replaceChildren(node("p","",error.message));notify(error.message);}}
async function refresh(append=false){const version=++state.request;$("refresh").disabled=true;$("more").disabled=true;notify("");try{const params=new URLSearchParams();if($("status").value)params.set("status",$("status").value);if(append&&state.next)params.set("before",state.next);const [overview,page]=await Promise.all([api("overview"),api("tasks?"+params)]);if(version!==state.request)return;state.items=append?[...state.items,...page.items]:page.items;state.next=page.next;renderStats(overview.counts);renderTasks();$("workspace").hidden=false;$("logout").hidden=false;$("login-view").hidden=true;if(typeof enableEvidenceNavigation==="function")enableEvidenceNavigation();if(state.selected&&!append)await loadDetail(state.selected);}catch(error){notify(error.message);}finally{$("refresh").disabled=false;$("more").disabled=false;}}
$("login-form").addEventListener("submit",async(event)=>{event.preventDefault();const button=event.currentTarget.querySelector("button");button.disabled=true;try{await api("login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("password").value})});$("password").value="";await refresh();}catch(error){notify(error.message);}finally{button.disabled=false;}});
$("logout").addEventListener("click",async()=>{try{await api("logout",{method:"POST"});showLogin();notify("");}catch(error){notify(error.message);}});
$("refresh").addEventListener("click",()=>refresh());$("more").addEventListener("click",()=>refresh(true));$("status").addEventListener("change",()=>{state.selected=null;state.detailRequest++;$("detail").replaceChildren(node("p","","请选择筛选后的任务查看详情。"));refresh();});
refresh();
